{ self }:
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.wayland.windowManager.trixie;

  toLua =
    v:
    if v == null then
      "nil"
    else if lib.isBool v then
      (if v then "true" else "false")
    else if lib.isInt v then
      toString v
    else if lib.isFloat v then
      toString v
    else if lib.isString v then
      ''"${lib.escape [ ''"'' "\\" ] v}"''
    else if lib.isList v then
      "{ " + lib.concatMapStringsSep ", " toLua v + " }"
    else if lib.isAttrs v then
      "{ " + lib.concatStringsSep ", " (lib.mapAttrsToList (k: val: "${k} = ${toLua val}") v) + " }"
    else
      throw "trixie hm-module: cannot convert ${builtins.typeOf v} to Lua";

  setLine = k: v: ''trixie.set("${k}", ${toLua v})'';

  generatedInitLua = ''
    -- AUTO-GENERATED by home-manager — do not edit this block manually.
    -- Source: wayland.windowManager.trixie in your HM config.

    ${lib.optionalString (cfg.settings != { }) (
      lib.concatStringsSep "\n" (lib.mapAttrsToList setLine cfg.settings)
    )}

    ${lib.optionalString (cfg.monitor != null) ''
      if not _G._monitor_configured then
        _G._monitor_configured = true
        trixie.set("monitor", ${toLua cfg.monitor})
      end
    ''}

    ${lib.optionalString (cfg.keybinds != [ ]) (
      lib.concatMapStringsSep "\n" (b: ''
        trixie.key(${toLua b.mods}, "${b.key}", function()
          ${b.action}
        end)'') cfg.keybinds
    )}

    ${lib.optionalString (cfg.autostart != [ ]) (
      lib.concatMapStringsSep "\n" (
        cmd: ''trixie.exec_once("${lib.escape [ ''"'' ] cmd}")''
      ) cfg.autostart
    )}

    ${lib.optionalString (cfg.rules != [ ]) ''
      trixie.rules.rules = {
          ${lib.concatMapStringsSep "\n" (
            r: "{ rule = ${toLua r.rule}, properties = ${toLua r.properties} },"
          ) cfg.rules}
          }''}
  '';

in
{
  options.wayland.windowManager.trixie = {
    enable = lib.mkEnableOption "Trixie Wayland compositor user configuration";

    package = lib.mkPackageOption pkgs "trixie" { };

    settings = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = { };
      example = lib.literalExpression ''
        {
          gap          = 6;
          outer_gap    = 9;
          border_width = 2;
          smart_gaps   = false;
          workspaces   = 9;
          font         = "JetBrainsMono Nerd Font";
          font_size    = 13;
          saturation   = 1.0;
          kb_layout    = "gb";
          repeat_rate  = 30;
          repeat_delay = 300;
        }
      '';
      description = "Key-value pairs passed to trixie.set() at startup.";
    };

    monitor = lib.mkOption {
      type = lib.types.nullOr (lib.types.attrsOf lib.types.anything);
      default = null;
      example = lib.literalExpression ''
        {
          name    = "eDP-1";
          width   = 1920;
          height  = 1080;
          refresh = 144;
          scale   = 1.0;
          x       = 0;
          y       = 0;
        }
      '';
      description = "Monitor configuration passed to trixie.set(\"monitor\", ...).";
    };

    keybinds = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            mods = lib.mkOption { type = lib.types.listOf lib.types.str; };
            key = lib.mkOption { type = lib.types.str; };
            action = lib.mkOption { type = lib.types.lines; };
          };
        }
      );
      default = [ ];
      example = lib.literalExpression ''
        [
          { mods = ["Mod4"]; key = "t"; action = "trixie.spawn(\"kitty\")"; }
          { mods = ["Mod4"]; key = "q"; action = "trixie.close()"; }
          { mods = ["Mod4" "Shift"]; key = "q"; action = "trixie.quit()"; }
        ]
      '';
      description = "Declarative keybinds. Each entry emits a trixie.key() call.";
    };

    autostart = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      example = [
        "dunst"
        "swaybg -m fill -c '#1e1e2e'"
        "nm-applet --indicator"
      ];
      description = "Commands passed to trixie.exec_once() at startup.";
    };

    rules = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            rule = lib.mkOption { type = lib.types.attrsOf lib.types.anything; };
            properties = lib.mkOption { type = lib.types.attrsOf lib.types.anything; };
          };
        }
      );
      default = [ ];
      example = lib.literalExpression ''
        [
          { rule.app_id = "pavucontrol"; properties.floating = true; }
          { rule.app_id = "firefox";     properties.workspace = 3; }
        ]
      '';
      description = "Window rules passed to trixie.rules.rules.";
    };

    configFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "Path to a hand-written init.lua to wrap with HM-generated settings.";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Lua code appended after the generated settings block in init.lua.";
    };

    extraModules = lib.mkOption {
      type = lib.types.attrsOf lib.types.path;
      default = { };
      example = lib.literalExpression ''
        {
          "theme" = ./modules/theme.lua;
          "binds" = ./modules/binds.lua;
          "bar"   = ./modules/bar.lua;
        }
      '';
      description = "Extra Lua files installed into ~/.config/trixie/modules/.";
    };

    systemd = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = { };
      internal = true;
      description = "Stub to satisfy way-displays.nix systemd injection.";
    };
  };

  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    # Publish the Wayland/Firefox environment into the systemd user session and
    # PAM environment so that applications launched by ly (or any other DM)
    # inherit the correct variables even before the compositor sets them.
    home.sessionVariables = {
      MOZ_ENABLE_WAYLAND = "1";
      MOZ_DBUS_REMOTE = "1";
      MOZ_WEBRENDER_FORCE = "1";
      EGL_PLATFORM = "wayland";
      NIXOS_OZONE_WL = "1";
      ELECTRON_OZONE_PLATFORM_HINT = "wayland";
      OZONE_PLATFORM = "wayland";
    };

    # Also emit into environment.d so systemd --user picks them up at
    # login (before the first graphical unit starts).
    xdg.configFile = {
      "environment.d/trixie-wayland.conf".text = ''
        MOZ_ENABLE_WAYLAND=1
        MOZ_DBUS_REMOTE=1
        MOZ_WEBRENDER_FORCE=1
        EGL_PLATFORM=wayland
        NIXOS_OZONE_WL=1
        ELECTRON_OZONE_PLATFORM_HINT=wayland
        OZONE_PLATFORM=wayland
      '';

      "trixie/_hm_generated.lua".text = generatedInitLua;
    }
    // {
      "trixie/init.lua" =
        if cfg.configFile != null then
          {
            text = ''
              -- Injected by home-manager — loads declarative settings first.
              require("_hm_generated")
              -- User init.lua (symlinked source: ${toString cfg.configFile})
            ''
            + builtins.readFile cfg.configFile;
          }
        else
          {
            text = ''
              -- init.lua — managed by home-manager.
              require("_hm_generated")
              ${cfg.extraConfig}
            '';
          };
    }
    // lib.mapAttrs' (
      name: src: lib.nameValuePair "trixie/modules/${name}.lua" { source = src; }
    ) cfg.extraModules;
  };
}
