{ self }:
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.wayland.windowManager.trixie;
  toml = pkgs.formats.toml { };

  toLua =
    v:
    if v == null then
      "nil"
    else if lib.isBool v then
      (if v then "true" else "false")
    else if lib.isInt v then
      toString v
    else if lib.isFloat v then
      toString v
    else if lib.isString v then
      ''"${lib.escape [ ''"'' "\\" ] v}"''
    else if lib.isList v then
      "{ " + lib.concatMapStringsSep ", " toLua v + " }"
    else if lib.isAttrs v then
      "{ " + lib.concatStringsSep ", " (lib.mapAttrsToList (k: val: "${k} = ${toLua val}") v) + " }"
    else
      throw "trixie hm-module: cannot convert ${builtins.typeOf v} to Lua";

  setLine = k: v: ''trixie.set("${k}", ${toLua v})'';

  generatedInitLua = ''
    -- AUTO-GENERATED by home-manager — do not edit this block manually.
    -- Source: wayland.windowManager.trixie in your HM config.

    ${lib.optionalString (cfg.settings != { }) (
      lib.concatStringsSep "\n" (lib.mapAttrsToList setLine cfg.settings)
    )}

    ${lib.optionalString (cfg.monitor != null) ''
      if not _G._monitor_configured then
        _G._monitor_configured = true
        trixie.set("monitor", ${toLua cfg.monitor})
      end
    ''}

    ${lib.optionalString (cfg.keybinds != [ ]) (
      lib.concatMapStringsSep "\n" (b: ''
        trixie.key(${toLua b.mods}, "${b.key}", function()
          ${b.action}
        end)'') cfg.keybinds
    )}

    ${lib.optionalString (cfg.autostart != [ ]) (
      lib.concatMapStringsSep "\n" (
        cmd: ''trixie.exec_once("${lib.escape [ ''"'' ] cmd}")''
      ) cfg.autostart
    )}

    ${lib.optionalString (cfg.rules != [ ]) ''
      trixie.rules.rules = {
          ${lib.concatMapStringsSep "\n" (
            r: "{ rule = ${toLua r.rule}, properties = ${toLua r.properties} },"
          ) cfg.rules}
          }''}
  '';

in
{
  options.wayland.windowManager.trixie = {
    enable = lib.mkEnableOption "Trixie Wayland compositor user configuration";

    package = lib.mkPackageOption pkgs "trixie" { };

    settings = lib.mkOption {
      type = lib.types.attrsOf lib.types.anything;
      default = { };
      description = "Key-value pairs passed to trixie.set() at startup.";
    };

    monitor = lib.mkOption {
      type = lib.types.nullOr (lib.types.attrsOf lib.types.anything);
      default = null;
      description = "Monitor configuration passed to trixie.set(\"monitor\", ...).";
    };

    keybinds = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            mods = lib.mkOption { type = lib.types.listOf lib.types.str; };
            key = lib.mkOption { type = lib.types.str; };
            action = lib.mkOption { type = lib.types.lines; };
          };
        }
      );
      default = [ ];
      description = "Declarative keybinds emitted as trixie.key() calls.";
    };

    autostart = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "Commands passed to trixie.exec_once() at startup.";
    };

    rules = lib.mkOption {
      type = lib.types.listOf (
        lib.types.submodule {
          options = {
            rule = lib.mkOption { type = lib.types.attrsOf lib.types.anything; };
            properties = lib.mkOption { type = lib.types.attrsOf lib.types.anything; };
          };
        }
      );
      default = [ ];
      description = "Window rules passed to trixie.rules.rules.";
    };

    configFile = lib.mkOption {
      type = lib.types.nullOr lib.types.path;
      default = null;
      description = "Path to a hand-written init.lua to wrap with HM-generated settings.";
    };

    extraConfig = lib.mkOption {
      type = lib.types.lines;
      default = "";
      description = "Lua code appended after the generated settings block.";
    };

    extraModules = lib.mkOption {
      type = lib.types.attrsOf lib.types.path;
      default = { };
      description = "Extra Lua files installed into ~/.config/trixie/modules/.";
    };
  };

  # ── Implementation ──────────────────────────────────────────────────────────
  config = lib.mkIf cfg.enable {
    home.packages = [ cfg.package ];

    # ── All xdg.configFile entries in ONE block ─────────────────────────────
    # Nix does not allow two separate `xdg.configFile = ...` assignments in
    # the same module — use // to merge everything into a single attrset.
    xdg.configFile =
      # 1. Generated settings block
      {
        "trixie/_hm_generated.lua".text = generatedInitLua;
      }
      # 2. init.lua — either wrapping a user file or fully managed
      // {
        "trixie/init.lua" =
          if cfg.configFile != null then
            {
              text = ''
                -- Injected by home-manager — loads declarative settings first.
                require("_hm_generated")

                -- User init.lua (symlinked source: ${toString cfg.configFile})
              ''
              + builtins.readFile cfg.configFile;
            }
          else
            {
              text = ''
                -- init.lua — managed by home-manager.
                require("_hm_generated")

                ${cfg.extraConfig}
              '';
            };
      }
      # 3. Extra module files — merged here, NOT in a separate assignment
      // lib.mapAttrs' (
        name: src: lib.nameValuePair "trixie/modules/${name}.lua" { source = src; }
      ) cfg.extraModules;
  };
}
